# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS-13'

steps:
- script: sudo xcode-select -p
  displayName: 'Check Xcode path'

- script: ls /Applications | grep Xcode
  displayName: 'List installed Xcode versions'

- script: xcodebuild -version
  displayName: 'Check Xcode version'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: '' # Specify your scheme name
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_15.2.app/Contents/Developer' # Adjust this path as needed

